# fly.toml app configuration file generated for project-batch-statement on 2025-02-12T12:26:50-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-batch-statement'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
